### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by CaptVJ**
added guestbook

### CODE REVIEW

**Comment by simcitynsun** [comment]
i think we will need more approval before linking to an external dependency like this buddy...

thoughts, @Will-radiodisney?

**Review by simcitynsun — APPROVED** [review]
i will approve reluctantly but will need another reviewer before merge

**Comment by Will-radiodisney** [comment]
I approve of this

**Comment by simcitynsun** [comment]
@CaptVJ you added an unrelated change to this PR in the future please make a new PR or explicitly call it out to those that have already reviewed

**Comment by simcitynsun** [comment]
> I approve of this

please press the add review button at top

**Review by Will-radiodisney — APPROVED** [review]
I approve of this VJ. Keep up the good work

**Comment by simcitynsun** [comment]
closes #4

**Pull request merged**
